# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e81f389af7fb88b501be8eb573e2bf628c21d92e93df5d669176e79ec7b70d280a544056a3337c81e977826855e38c5d4d823ad8e6d5b8e4ec2d4d7875e2b16

test:
  secret_key_base: d3c87464c496a3a603e7ba155b876ff412da6d715225dc008a643dd3f6b51b3f2562b353ffa0eca1cf7418b27da10f9b7cd55dc4de9348b4328123b758dff5de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
